# Generated by Django 2.2.5 on 2022-07-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bedroooms',
            new_name='bedrooms',
        ),
    ]
