# Generated by Django 2.2.5 on 2022-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220719_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cleanliness',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
